classDiagram
ROOT <|-- Sensorboard
Sensorboard : humidity
Sensorboard : waterlevel
Sensorboard : ndir_co2
Sensorboard : ambient_light
Sensorboard : fan
Sensorboard : led
Sensorboard : pump
Sensorboard : emoji